var car = new Array('Inova','BMW','Benz','Fortuner')
console.log(car[0])
console.log(car[1])
console.log(car[2])
console.log(car[3])

console.log('======================')
var bike = new Array('Activa','Deo','Honda','Royal Enfield')
console.log(bike[0])
console.log(bike[1])
console.log(bike[2])
console.log(bike[3])

console.log('======================')
var colors = new Array('Red','Green','Blue','Pink')
console.log(colors[0])
console.log(colors[1])
console.log(colors[2])
console.log(colors[3])

console.log('======================')
var fruit = new Array('Apple','Banana','Grapes','Water Melon') 
console.log(fruit[0])
console.log(fruit[1])
console.log(fruit[2])
console.log(fruit[3])

console.log('======================')
var mobile = new Array('Redme','Oppo','ViVo','Samsung')
console.log(mobile[0])
console.log(mobile[1])
console.log(mobile[2])
console.log(mobile[3])
