const  word = 'Hellow World'
const uppercase = word.toUpperCase(word)
console.log('After uppercase',uppercase)
const lowercase = word.toLowerCase(word)
console.log('After lowercase',lowercase)
const charAt = word.charAt(5)
console.log('After CharAt',charAt)
const indexofd = word.indexOf('d')
console.log('Index of d',indexofd)
const concatString = word.concat('Hellllllllllowww')
console.log('After Concat',concatString)
const includes = word.includes('el',0)
console.log('is includes',includes)
const replace = word.replace('ell','ooo')
console.log('After replace',replace)
const split = word.split('o',4)
console.log('After split',split)
const substr = word.substr(0,9)
console.log('After substr',substr)
const search = word.search('o')
console.log('After search',search)
const trimm  = word.trim()
console.log('After trim',trimm)

console.log('=====================================================')
const  fruit = 'Apple'
const uppercase1 = fruit.toUpperCase(fruit)
console.log('After uppercase',uppercase1)
const lowercase1 = fruit.toLowerCase(fruit)
console.log('After lowercase',lowercase1)
const charAt1 = fruit.charAt(1)
console.log('After CharAt',charAt1)
const indexofp = fruit.indexOf('p')
console.log('Index of p',indexofp)
const concatString1 = fruit.concat(' Mango Grapes')
console.log('After Concat',concatString1)
const includes1 = fruit.includes('le',0)
console.log('is includes',includes1)
const replace1 = fruit.replace('le','ss')
console.log('After replace',replace1)
const split1 = fruit.split('l',3)
console.log('After split',split1)
const substr1 = fruit.substr(0,2)
console.log('After substr',substr1)
const search1 = fruit.search('e')
console.log('After search',search1)
const trimm1  = fruit.trim()
console.log('After trim',trimm1)


console.log('=============================================')
const  item = 'Kajal Lipstick'
const uppercase2 = item.toUpperCase(item)
console.log('After uppercase',uppercase2)
const lowercase2 = item.toLowerCase(item)
console.log('After lowercase',lowercase2)
const charAt2 = item.charAt(3)
console.log('After CharAt',charAt2)
const indexofk = item.indexOf('k')
console.log('Index of k',indexofk)
const concatString2 = item.concat(' Bangle Earrings')
console.log('After Concat',concatString2)
const includes2 = item.includes('qqq',0)
console.log('is includes',includes2)
const replace2 = item.replace('pst','abc')
console.log('After replace',replace2)
const split2 = item.split('s',4)
console.log('After split',split2)
const substr2 = item.substr(0,5)
console.log('After substr',substr2)
const search2 = item.search('K')
console.log('After search',search2)
const trimm2  = item.trim()
console.log('After trim',trimm2)


console.log('===========================================')
const  color = 'Pink Blue'
const uppercase3 = color.toUpperCase(color)
console.log('After uppercase',uppercase3)
const lowercase3 = color.toLowerCase(color)
console.log('After lowercase',lowercase3)
const charAt3 = color.charAt(3)
console.log('After CharAt',charAt3)
const indexofi = color.indexOf('i')
console.log('Index of i',indexofi)
const concatString3 = color.concat(' Brown')
console.log('After Concat',concatString3)
const includes3 = color.includes('jj',0)
console.log('is includes',includes3)
const replace3 = color.replace('Pin','PPP')
console.log('After replace',replace3)
const split3 = word.split('l',4)
console.log('After split',split3)
const substr3 = color.substr(0,2)
console.log('After substr',substr3)
const search3 = color.search('B')
console.log('After search',search3)
const trimm3  = color.trim()
console.log('After trim',trimm3)

console.log('======================================')
const  car = 'Benz Inova Fortuner'
const uppercase4 = car.toUpperCase(car)
console.log('After uppercase',uppercase4)
const lowercase4 = car.toLowerCase(car)
console.log('After lowercase',lowercase4)
const charAt4 = car.charAt(3)
console.log('After CharAt',charAt4)
const indexofI = car.indexOf('I')
console.log('Index of I',indexofI)
const concatString4 = car.concat(' Audi Shiftdeire')
console.log('After Concat',concatString4)
const includes4 = car.includes('er',0)
console.log('is includes',includes4)
const replace4 = car.replace('Benz','AAAA')
console.log('After replace',replace4)
const split4 = car.split('v',4)
console.log('After split',split4)
const substr4 = car.substr(0,5)
console.log('After substr',substr4)
const search4 = car.search('F')
console.log('After search',search4)
const trimm4  = car.trim()
console.log('After trim',trimm4)

console.log('=============================================')
const Bike = 'ActiveHondaDeo'
const uppercase5 = Bike.toUpperCase(Bike)
console.log('After uppercase',uppercase5)
const lowercase5 = Bike.toLowerCase(Bike)
console.log('After lowercase',lowercase5)
const charAt5 = Bike.charAt(4)
console.log('After CharAt',charAt5)
const indexofD = Bike.indexOf('D')
console.log('Index of D',indexofD)
const concatString5 = Bike.concat(' Fascino')
console.log('After Concat',concatString5)
const includes5 = Bike.includes('Deo',0)
console.log('is includes',includes5)
const replace5 = Bike.replace('Deo','Beo')
console.log('After replace',replace5)
const split5 = Bike.split('v',4)
console.log('After split',split5)
const substr5 = Bike.substr(0,6)
console.log('After substr',substr5)
const search5 = Bike.search('n')
console.log('After search',search5)
const trimm5  = Bike.trim()
console.log('After trim',trimm5)


console.log('=============================================')
const  board = 'Blackboard Whiteboard'
const uppercase6 = board.toUpperCase(board)
console.log('After uppercase',uppercase6)
const lowercase6 = board.toLowerCase(board)
console.log('After lowercase',lowercase6)
const charAt6 = board.charAt(6)
console.log('After CharAt',charAt6)
const indexofh = board.indexOf('I')
console.log('Index of h',indexofh)
const concatString6 = board.concat(' Plainboard')
console.log('After Concat',concatString6)
const includes6 = board.includes('hite',0)
console.log('is includes',includes6)
const replace6 = board.replace('White','Pink')
console.log('After replace',replace6)
const split6 = board.split('W',11)
console.log('After split',split6)
const substr6 = board.substr(0,5)
console.log('After substr',substr6)
const search6 = board.search('d')
console.log('After search',search6)
const trimm6  = board.trim()
console.log('After trim',trimm6)

console.log('======================================')
const value = 'Hiii Welcome'
const uppercase7 = value.toUpperCase(value)
console.log('After uppercase',uppercase7)
const lowercase7 = value.toLowerCase(value)
console.log('After lowercase',lowercase7)
const charAt7 = value.charAt(7)
console.log('After CharAt',charAt7)
const indexofH = value.indexOf('H')
console.log('Index of H',indexofH)
const concatString7 = value.concat(' Byeeee')
console.log('After Concat',concatString7)
const includes7 = value.includes('com',0)
console.log('is includes',includes7)
const replace7 = value.replace('come','go')
console.log('After replace',replace7)
const split7 = value.split('W',4)
console.log('After split',split7)
const substr8 = value.substr(0,5)
console.log('After substr',substr8)
const search8 = value.search('o')
console.log('After search',search8)
const trimm7  = value.trim()
console.log('After trim',trimm7)

console.log('================================================')






